# Generated by Django 5.0.4 on 2024-04-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='AdminProfile',
        ),
    ]
