# Generated by Django 5.0.4 on 2024-04-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customer_avatar'),
        ),
    ]
