# Generated by Django 5.0.4 on 2024-04-29 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^\\d{10,15}$')], verbose_name='Mobile Number'),
        ),
    ]
