# Generated by Django 5.0.4 on 2024-05-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_id',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Customer ID'),
        ),
    ]
