# Generated by Django 5.0.4 on 2024-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='customer_id',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Customer ID'),
        ),
    ]
