# Generated by Django 5.0.4 on 2024-08-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('rating_type', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255, verbose_name='Rating Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
