# Generated by Django 5.0.4 on 2024-10-09 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_wishlist_added_date_alter_wishlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 10, 9, 14, 37, 32, 772656, tzinfo=datetime.timezone.utc)),
        ),
    ]
