# Generated by Django 5.0.4 on 2024-10-09 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_wishlist_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
