# Generated by Django 5.0.4 on 2024-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_active_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_amont',
            field=models.BigIntegerField(default=0),
        ),
    ]
