# Generated by Django 5.0.4 on 2024-04-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_total_amont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_amont',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
