# Generated by Django 5.0.4 on 2024-04-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cartitem_total_amont_cartitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
