# Generated by Django 5.0.4 on 2024-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartitem_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
