# Generated by Django 5.0.4 on 2024-05-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cartitem_color_alter_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
    ]
