# Generated by Django 5.0.4 on 2024-05-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_abandoned'),
        ('products', '0014_alter_variation_color_alter_variation_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='products.variation'),
        ),
    ]
