# Generated by Django 5.0.4 on 2024-05-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_cartitem_color_remove_cartitem_size_and_more'),
        ('products', '0016_variation_image_variation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='products.variation'),
        ),
    ]
