# Generated by Django 5.0.4 on 2024-06-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
