# Generated by Django 5.0.4 on 2024-08-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='color',
        ),
        migrations.AddField(
            model_name='variation',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='variations', to='products.color'),
        ),
    ]
