# Generated by Django 5.0.4 on 2024-08-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_variation_color_variation_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='color',
            new_name='colors',
        ),
    ]
