# Generated by Django 5.0.3 on 2024-04-13 19:59

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(products.models.get_default_product_category), related_name='product_list', to='products.productcategory'),
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
