# Generated by Django 5.0.4 on 2024-08-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_size_color_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='sizes',
        ),
        migrations.AddField(
            model_name='color',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='products.size'),
        ),
    ]
