# Generated by Django 5.0.4 on 2024-09-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_color_sizes_color_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.productimage'),
            preserve_default=False,
        ),
    ]
