# Generated by Django 5.0.3 on 2024-04-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_size_alter_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Size',
            new_name='size',
        ),
    ]
