# Generated by Django 5.0.4 on 2024-04-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_color_quantity_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set(),
        ),
    ]
