# Generated by Django 5.0.4 on 2024-04-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_variation_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='discounted_percentage',
        ),
    ]
