# Generated by Django 5.0.4 on 2024-05-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_cartitem_color_remove_cartitem_size_and_more'),
        ('products', '0014_alter_variation_color_alter_variation_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
