# Generated by Django 5.0.4 on 2024-05-06 14:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_delete_color_delete_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='product/images/variations'),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='variation',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
