# Generated by Django 5.0.4 on 2024-05-11 04:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_variation_image_variation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='product/images/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='product/category/icons/'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='product/images/variations'),
        ),
    ]
