# Generated by Django 5.0.4 on 2024-05-29 13:50

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_coverpagecarousel_alter_product_image_latestarival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supercategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='super_category',
            field=models.ForeignKey(null=True, on_delete=models.SET(products.models.get_default_product_super_category), to='products.supercategory'),
        ),
    ]
