# Generated by Django 5.0.4 on 2024-06-27 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_supercategory_productcategory_super_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product'),
        ),
    ]
